//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronmanSaveBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronmanSaveBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred. Backup operation stopped..
        /// </summary>
        internal static string AutoBackupException {
            get {
                return ResourceManager.GetString("AutoBackupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created backup for Campaign {0}.
        /// </summary>
        internal static string BackupCreatedSuccess {
            get {
                return ResourceManager.GetString("BackupCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Error.
        /// </summary>
        internal static string BackupErrorCaption {
            get {
                return ResourceManager.GetString("BackupErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Operation Successful.
        /// </summary>
        internal static string BackupSuccessCaption {
            get {
                return ResourceManager.GetString("BackupSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the Campaign that this backup belongs to. Backup was not restored..
        /// </summary>
        internal static string CampaignNotFound {
            get {
                return ResourceManager.GetString("CampaignNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this box?.
        /// </summary>
        internal static string CloseBoxWarning {
            get {
                return ResourceManager.GetString("CloseBoxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Backups?.
        /// </summary>
        internal static string DeleteAllBackupCaption {
            get {
                return ResourceManager.GetString("DeleteAllBackupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing &apos;Yes&apos; will DELETE ALL BACKUPS in your backups folder. This is NOT reversible..
        /// </summary>
        internal static string DeleteAllBackupWarning {
            get {
                return ResourceManager.GetString("DeleteAllBackupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Backups Successfully Deleted..
        /// </summary>
        internal static string DeleteAllSuccess {
            get {
                return ResourceManager.GetString("DeleteAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while trying to delete existing backups. Please close XCOM 2, restart this application, and try again..
        /// </summary>
        internal static string ExceptionOnDelete {
            get {
                return ResourceManager.GetString("ExceptionOnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore the selected backup because the Ironman Save and/or the Backup Save is in use..
        /// </summary>
        internal static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filepath found for the selected backup..
        /// </summary>
        internal static string FilepathNotFound {
            get {
                return ResourceManager.GetString("FilepathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected does not exist or cannot be found..
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File/Folder Selected.
        /// </summary>
        internal static string FolderNotFoundCaption {
            get {
                return ResourceManager.GetString("FolderNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred.
        /// </summary>
        internal static string GeneralErrorCaption {
            get {
                return ResourceManager.GetString("GeneralErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File In Use.
        /// </summary>
        internal static string InUseCaption {
            get {
                return ResourceManager.GetString("InUseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled.
        /// </summary>
        internal static string InvalidChoiceCaption {
            get {
                return ResourceManager.GetString("InvalidChoiceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The choice you selected is invalid..
        /// </summary>
        internal static string InvalidChoiceWarning {
            get {
                return ResourceManager.GetString("InvalidChoiceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path Error.
        /// </summary>
        internal static string InvalidPathCaption {
            get {
                return ResourceManager.GetString("InvalidPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected an invalid file for restoration..
        /// </summary>
        internal static string InvalidRestoreFile {
            get {
                return ResourceManager.GetString("InvalidRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file selected for restoration does not exist..
        /// </summary>
        internal static string MissingRestoreFile {
            get {
                return ResourceManager.GetString("MissingRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ironman Saves found in the selected location..
        /// </summary>
        internal static string NoIronmanSaves {
            get {
                return ResourceManager.GetString("NoIronmanSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup?.
        /// </summary>
        internal static string ReplaceExistingCaption {
            get {
                return ResourceManager.GetString("ReplaceExistingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing &apos;Yes&apos; will replace the existing Ironman Save for this campaign. Please ensure you have a backup of your current save prior to recovery..
        /// </summary>
        internal static string ReplaceExistingWarning {
            get {
                return ResourceManager.GetString("ReplaceExistingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Error.
        /// </summary>
        internal static string RestoreErrorCaption {
            get {
                return ResourceManager.GetString("RestoreErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration Successful.
        /// </summary>
        internal static string RestoreSuccessCaption {
            get {
                return ResourceManager.GetString("RestoreSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored save for Campaign {0}.
        /// </summary>
        internal static string SaveRestoredSuccess {
            get {
                return ResourceManager.GetString("SaveRestoredSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save_IRONMAN- Campaign {0}.
        /// </summary>
        internal static string SaveRestoreName {
            get {
                return ResourceManager.GetString("SaveRestoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove all backups in selected folder..
        /// </summary>
        internal static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Weird Happened.
        /// </summary>
        internal static string WeridCaption {
            get {
                return ResourceManager.GetString("WeridCaption", resourceCulture);
            }
        }
    }
}
